## Rubric
Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Srikar Eranky: Research Question original draft, Background info original draft, Hypothesis Original Draft, Data Overview, Dataset #1 Wrangling/Tidying
- Weston Zong: Updated research question, background, hypothesis, and ethics based on provided feedback. Copied over team expectations. Updated timeline.
- Bob Barker:  Analysis, Software, Visualization
- Siddhartha Sarvepally: Dataset #2 Cleaning
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Is there a statistically significant relationship between the prestige of a film cast, measured by major award nominations and wins, and how the film is rated by viewers, measured by IMDb ratings, controlling for genre and release year?

## Background and Prior Work

We are trying to determine if we can find a relationship between a movie cast's stardom level and the movie's performance. Films packed with celebrities often can gain a lot of initial interest in trailers and marketing as there are people that show up at movie theaters just to see a specific celebrity on the screen. However, factors like negative online ratings and word of mouth reactions can tank a movie's performance a lot more than any celebrity can boost it, so it is hard to determine for any given movie how well it will perform. We will look for long term trends to discover if celebrity status is a good enough sign of movie success or not. We will define ways to measure stardom and measure movie success.

In "A Quantitative Study on the Effect of Cast Member Celebrity on Film Success," researchers used a regression model and analyzed the top 20 grossing films from 2015-2019, so a total of 100 movies total. They discovered that increased celebrity status correlated with both increased revenue and improved public perception. We question the conclusion of this article as taking the top 20 grossing films can mislead analysis as it doesn't account for cases where a movie "flops" but has celebrities. The author notes constraints such as using only the top 7 actors/actresses in their stardom metrics. Moreover, the study uses the actor/actress's current stardom level, which does not work in cases where the movie makes the actor/actress famous post-release. We can address these issues by accounting for a larger amount of the cast in stardom and measuring the actor/actress's popularity at the time of movie release. Additionally, 100 movies is likely not a large enough sample size and these movies were pulled up until 2019; Now a lot of marketing is done through social media which was not such a big tactic back then. Therefore, we can try to acquire data from a greater amount of movies and also use more recent movies.

Additionally, in "The Power of Stars: Do Star Actors Drive the Success of Movies?" the researchers examine whether hiring star actors measurably increases a film’s expected theatrical revenue, using prediction‑market data and stock‑market style reactions around casting announcements. The study finds that, on average, attaching a star adds a few million dollars to a movie’s expected box‑office, quantifying star power to 3‑million‑dollar increase in revenue rather than treating it as a vague marketing benefit. Elberse shows that this effect is not constant. The marginal impact of a new star is larger when the existing cast is already strong, meaning other members within groups are important rather than simple “one big name is enough” logic. By focusing on expected revenue before release, the paper frames stars as a costly but quantifiable investment whose value must be weighed against high salaries and profit participation. However, a "star" is defined as actors who already have HSX StarBonds, which requires at least two major roles. That excludes emerging talent and underestimates cases where a film itself creates a star which this paper ignores, a similar flaw to the one found in the first document.

In determining how we determine "prestige" of a movie's cast, we came across "Factors Affecting the Financial Success of Motion Pictures: What is the Role of Star Power?" in which they coin the term "star power" for this metric. In this paper they describe using the number of nominations for Academy awards and average lifetime gross revenue of films involving the specific celebrity. Again, to avoid previously discussed issues, we wlil have to make sure we use these stats respective to the time in wihch the movie came out, not present day. This document also reveals some surprising findings like that the time of year of the movie's release didn't seem to matter, nor did the genre make a significant impact. We will still take these into account when analyzing these movies, as we can never be completely sure if there truly is no effect from these features. They end up acknowledging how subjective star power is given how everyone has their unique perception and is thus difficult to measure. This only reinforces the notion that we should find many different ways to measure stardom.

We also found a similar project on Github, "IMDb_ratings_analysis" that goes more broad and tries to find multiple parameters for a movie's success, as well as predict if a movie is going to do well based on discovered factors. They even perform plot analysis as part of their analysis. We do not plan on going this far with our project, but these are good stretch goals to include. For now, we will just focus on the celebrity status of our movie casts.






- "A Quantitative Study on the Effect of Cast Member Celebrity on Film Success" (Kwan, Scheepers, 2022): * Finding: Using a cross-sectional regression model, this study found that while a star-studded cast significantly boosts commercial success (box office) and public perception (IMDb ratings), it has almost zero correlation with "artistic merit" (metacritic score). https://www.researchgate.net/publication/369955734_The_Fault_in_Our_Stars_A_Quantitative_Study_on_the_Effect_of_Cast_Member_Celebrity_on_Film_Success


- "The Power of Stars: Do Star Actors Drive the Success of Movies?" (Elberse, 2007): * Finding:  Star power was quantified through two factors: economic reputation (average past box-office draw from the actor's prior five films) and artistic reputation (points from recent awards). Testing was done with regressions, interactions with existing cast strength, and robustness to alternative windows, star thresholds, and realized revenue validation. Concludes that they were not able to find a strong relationship between the stars in a movie cast and the revenue of the movie (and thus valuation of its film studio).
https://www.hbs.edu/faculty/Pages/item.aspx?num=23770 

- "Factors Affecting the Financial Success of Motion Pictures: What is the Role of Star Power?" (Jen-Yuan Yang, Geethanjali Selvaretnam) Finding: Star power was quantified through award nominations and economic success. They used the least squares regression model, and found no significant correlation to box office success. https://www.st-andrews.ac.uk/~wwwecon/repecfiles/4/1501-ori.pdf

- https://github.com/charfimohamed/IMDb_ratings_analysis

## Hypothesis

We hypothesize that the prestige of a film cast will not have a statistically significant positive association with IMDb rating, after controlling for genre and release year. Although Kwan and Scheeper's research found a positive correlation between star level public perception through IMDb ratings, as mentioned in the background section, we have identified areas of improvement in their set up that could change our findings. Kwan and Scheeper also found a positive relationship between celebrity presence and commercial performance, but other research from Elberse and Yang found no strong relationship between these two variables.

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
- Dataset #1
  - Dataset Name: IMDB Movies Dataset
  - Link to the dataset: https://www.kaggle.com/datasets/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows
  - Number of observations: 1000
  - Number of variables: 16
  - Description of the variables most relevant to this project: We will likely use the IMDb rating as the dependent variable in this project. The dataset also has a column for the top star, the 2nd star, 3rd star, and 4th star actors in the movie - we will use all of these to create a feature representing the "strength" of the star cast. We also may use the "Gross" variable that represents how much the movie grossed as an output variable to determine whether the strength of the cast influenced how much money the movie made.
  - Descriptions of any shortcomings this dataset has with repsect to the project: The only thing this dataset doesn't really have is a metric for the strength of the star cast - we will have to engineer that feature manually.
- Dataset #2 (if you have more than one!)
  - Dataset Name: Movies Box office Dataset (2000-2024)
  - Link to the dataset: https://www.kaggle.com/datasets/aditya126/movies-box-office-dataset-2000-2024
  - Number of observations: 4955
  - Number of variables: 13
  - Description of the variables most relevant to this project: We will likely match the movies in the dataset with the ones in the previous dataset to explore the relationship between domestic % and foreign %. These are two variables in this dataset that may be confounding variables, as the percentage of movie revenue that is domestic vs foreign could be influenced by factors other than just the strength of the star cast. These variables could, conversely, demonstrate a strong correlation between star cast and movie revenue/rating, as people in foreign countries may be more willing to watch a Hollywood movie because of certain actors. 
  - Descriptions of any shortcomings this dataset has with repsect to the project: The dataset may not have all the same movies in the first dataset, so there may be a very small sample of movies that overlap in both datasets that we can use for our analysis. This dataset also does not have any star cast information - only percentage of revenue generated by domestic and foreign as well as the genre and year of the movie. 

We plan to combine these datasets by finding the overlapping movies and checking if there is a relationships between foreign and domestic % of revenue and the star cast strength, as well as explore whether the percentage of revenue generated in other countries could be a confounding variable.

In [17]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [1]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
%pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
# datafiles = [
#     { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
#     { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
# ]

# get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Requirement already satisfied: requests in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (2.32.5)
Requirement already satisfied: tqdm in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/surshah/Desktop/COGS_108/.venv/lib/python3.12/site-packages (from requests) (2026.2.25)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Top 1000 Movies on IMDB

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

### Top 1000 Movies on IMDB overview

Overview of the dataset: 
This dataset contains 1,000 highest-rated movies and TV shows on IMDB. We removed three columns that weren't useful for our analysis, the movie poster link, content rating, and plot summary. We had around 750 tiles left over that we worked with. 

Key Metrics we use include IMDb Rating, Metascore, Gross, No_of_Votes, Star1–Star4. Each of these columns and values have different meanings. IMDb is a score from 1 to 10 and is based on votes from IMDb users. Soemthing to note though is that the dataset is the top 1,000 films so every title is already a high score so the patterns might not be that good or prominent. The Metascore is a score from 0 to 100 based on reviews from professional film critics so this is different from the crowd sourced score. Most of the films in this dataset score are pretty high scores which works since all of these are good movies. Gross is how much money the film made. Something to note here is that depending on the time period that the films were produced, the value of the gross also changes. No_of_votes is how many IMDb users rated the film. More votes is usually better. Star1–Star4 are the four members of the cast that are the main people.

Concerns and biases include that we don't have almost 25% of the data since we dropped values that had missing values. Most of the films that were dropped are from older films. Another concern is that a lot of the value behind these films isn't adjusted or anything for inflation so the costs are a bit varied. IMDB ratings also don't represent everyone equally since certain films have differnt audiences. 

Overall this dataset is a really good one for us to use.

In [19]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
!pip install pandas
import pandas as pd
top_1000 = pd.read_csv('data/00-raw/imdb_top_1000.csv')
top_1000.head()

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [3]:
top_1000.isnull()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True
999,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True

We felt that poster link, certificate, and overview were not very relevant to our research question. We are measuring the relationship between the strength of the star cast and movie rating/revenue. The poster link and certificate would not be of much help, and not many people watch movies because of the overview, which we would also need to transform into vectors or embeddings to determine whether it could be a confounding variable.

In [4]:
# remove irrelevant columns, then drop nulls
top_1000 = top_1000[['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating', 'Meta_score', 'Director', 'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross']]
top_1000.to_csv('data/01-interim/imdb_top_1000_relevant_cols.csv')
rows_to_drop = top_1000[top_1000.isnull().any(axis=1)]
rows_to_drop

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
18,Hamilton,2020,160 min,"Biography, Drama, History",8.6,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
20,Soorarai Pottru,2020,153 min,Drama,8.6,NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
30,Seppuku,1962,133 min,"Action, Drama, Mystery",8.6,85.0,Masaki Kobayashi,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,42004,NaN
32,It's a Wonderful Life,1946,130 min,"Drama, Family, Fantasy",8.6,89.0,Frank Capra,James Stewart,Donna Reed,Lionel Barrymore,Thomas Mitchell,405801,NaN
46,Hotaru no haka,1988,89 min,"Animation, Drama, War",8.5,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,Blowup,1966,111 min,"Drama, Mystery, Thriller",7.6,82.0,Michelangelo Antonioni,David Hemmings,Vanessa Redgrave,Sarah Miles,John Castle,56513,NaN
995,Breakfast at Tiffany's,1961,115 min,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,Giant,1956,201 min,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
998,Lifeboat,1944,97 min,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,The 39 Steps,1935,86 min,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [5]:
# clean dataframe by dropping all Nan rows
top_1000 = top_1000.dropna()
top_1000.to_csv('data/01-interim/imdb_top_1000_dropna.csv')
top_1000.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
990    False
991    False
992    False
994    False
997    False
Length: 750, dtype: bool

In [6]:
top_1000.isnull().any(axis=1).any()

np.False_

This indicates that there are no more rows with at least one null value - all values in the dataframe or non-null. We decided to drop these rows instead of filling them because we did not want to use estimates for the gross revenue generated by the movie, as that is our output variable and we wanted to have ground truth data to do our analysis. Because of this, we decided to drop all rows with a null, since a lot of values in the "Gross" column were null. A better strategy for this in the future may be to look for values in dataset #2 that overlap with this dataset and fill in the gross revenue values from the other dataset.

In [7]:
top_1000[['IMDB_Rating', 'Meta_score', 'Gross']].describe()

       IMDB_Rating  Meta_score
count   750.000000  750.000000
mean      7.934800   77.460000
std       0.289103   12.493967
min       7.600000   28.000000
25%       7.700000   70.000000
50%       7.900000   78.000000
75%       8.100000   86.000000
max       9.300000  100.000000

In [8]:
top_1000['Gross'].dtypes

dtype('O')

As we can see, the data type of the "Gross" column is String, which means they need to be converted back to an integer. We tried describing all the numeric output variables above, but the absence of the Gross column indicates that it needs to be cleaned.

In [9]:
top_1000['Gross'] = top_1000['Gross'].str.replace(',', '', regex=False).astype('Int64') # this line of code was partially generated by
# github copilot using the prompt "Convert a pandas df column from string to int - the values may have commas"
top_1000['Gross'].dtypes

Int64Dtype()

In [10]:
top_1000[['IMDB_Rating', 'Meta_score', 'Gross']].describe()

       IMDB_Rating  Meta_score             Gross
count   750.000000  750.000000             750.0
mean      7.934800   77.460000   74952069.305333
std       0.289103   12.493967  113328042.802158
min       7.600000   28.000000            1305.0
25%       7.700000   70.000000         5014811.5
50%       7.900000   78.000000        31900000.0
75%       8.100000   86.000000       98091570.75
max       9.300000  100.000000       936662225.0

In [11]:
top_1000.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469
1,The Godfather,1972,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411
2,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444
3,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000
4,12 Angry Men,1957,96 min,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000

In [12]:
top_1000.to_csv('data/02-processed/imdb_top_1000_cleaned.csv')

### Dataset #2  -- Movies Box office Dataset (2000-2024)

The Movie Box Office Dataset provides a detailed analysis of the perofrmance of movies from 2000 to 2024. It is measured in the global box office preformance. Some key features include: Timeframe, Metrics, Genres, and Insights. For the Timeframe, this is a collection of movies from 2000 to 2024. For the metrics, the dataset includes revenue, production budget, profit margins, and more, but these were the most notable. For genres, the dataset covers a variety of genres to get a vast breadth of movies to be covered. Lastly, for the insights, the dataset kaggle website states that it is "ideal for trend analysis, profitablity studies, and forcasting."

Looking into the dataset, there are 4955 unique movies that measure the dollar amount it made worldwide and domestically. This dollar amount is measured in U.S.D. I think this is vital because if there is an American movie with a stronger cast, it would probably preform better domestically here in the US because we are familiar with many big names in the cast (E.G. Ryan Gosling). Alongside this, there are aspects that measure how much of the domestic revenue makes up the global in terms of a percentage. Using the percentage makes it pretty easy for us to get an idea of how domestic preformance compares to the global. It does the same for foreign values and percentages as well. Lastly, the dataset contains each movies rating out of 10 from reputable sources.

The rating feature is vital in combination with the others as we can see how a movie preforms in terms of critic ratings, and the amount of money that the movie brings in. The movies are rated by a score of 0-10 and can include decimals (EX: 7.5 / 10).I do think a slight limitation from this dataset is that it does not contain notable cast members for each movie. For our project this may be a little bit harder to work with for the needs of our project. A potential solution would be to merge this dataset with another source (maybe IMDB) to get a metric on the cast. I am thinking of having a numerical value for the strength of the cast and that can allow us to use this dataset to the full capability. 

Overall, this dataset is very solid for the purpose of our project in terms of the movie performance aspect. It gives a solid baseline and great metrics to measure mover 4900 movies' performances.

In [16]:
import pandas as pd

enhanced_box_office_data = pd.read_csv('data/00-raw/enhanced-box-office-data-2000-2024.csv')
enhanced_box_office_data.drop(columns=['Year', 'Original_Language', 'Genres', 'Production_Countries'], inplace=True)
enhanced_box_office_data.head()

# kept the domestic and foreign percent columns as they could be relevant to seeing if bigger actors made a difference in domestic box office numbers. Dropped Language, Genre, and Production_countries as it doesn't directly affect our analysis that we are looking for

,Rank,Release Group,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Rating,Vote_Count
0,1,Mission: Impossible II,546388108.0,215409889.0,39.4,330978219.0,60.6,6.126/10,6741.0
1,2,Gladiator,460583960.0,187705427.0,40.8,272878533.0,59.2,8.217/10,19032.0
2,3,Cast Away,429632142.0,233632142.0,54.4,196000000.0,45.6,7.663/10,11403.0
3,4,What Women Want,374111707.0,182811707.0,48.9,191300000.0,51.1,6.45/10,3944.0
4,5,Dinosaur,349822765.0,137748063.0,39.4,212074702.0,60.6,6.544/10,2530.0

In [17]:
enhanced_box_office_data['Rating'] = enhanced_box_office_data['Rating'].str.split('/').str[0].astype(float)
enhanced_box_office_data.set_index('Release Group', inplace=True)

# to tidy up the dataset, we changed the rating column into a float so that it is easy to make calculations from it, as well as made the title the index so that it is easily identifiable.

In [18]:
print(enhanced_box_office_data.shape)
print(enhanced_box_office_data.isna().sum())

# dataset now has 8 columns with 5000 movies. There is missing values across the genres, rating, vote_count, original_language, and production_countries columns.

(5000, 8)
Rank            0
$Worldwide      0
$Domestic       0
Domestic %      0
$Foreign        0
Foreign %       0
Rating        170
Vote_Count    170
dtype: int64

In [19]:
rows_to_drop = enhanced_box_office_data[enhanced_box_office_data.isnull().any(axis=1)]

rows_to_drop

# it looks like special releases of movies like re-releases and dircetor's cuts as well as specific episodes are missing data, it makes sense to remove them so there isn't a repeat of data.

,Rank,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Rating,Vote_Count
Release Group,,,,,,,,
The Exorcist 2000 Director's Cut,39,112053066.0,39671011.0,35.4,72382055.0,64.6,NaN,NaN
Widow of St. Pierre,160,7193889.0,3193889.0,44.4,4000000.0,55.6,NaN,NaN
The Jungle Book 2000 Re-release,170,4466472.0,0.0,0.0,4466472.0,100.0,NaN,NaN
Blood Simple 2000 Re-release,192,2068701.0,1701855.0,82.3,366846.0,17.7,NaN,NaN
Rear Window 2000 Re-release,199,1699210.0,1574607.0,92.7,124603.0,7.3,NaN,NaN
...,...,...,...,...,...,...,...,...
One Direction: This Is Us 2024 Re-release,158,10452473.0,263511.0,2.5,10188962.0,97.5,NaN,NaN
Ruki vverkh!,166,9630048.0,0.0,0.0,9630048.0,100.0,NaN,NaN
The Chosen: S4 Episodes 4-6,167,9482744.0,9482744.0,100.0,0.0,0.0,NaN,NaN
The Boy with Pink Trousers,168,9449929.0,0.0,0.0,9449929.0,100.0,NaN,NaN
The Chosen: S4 Episodes 7-8,190,7768191.0,7729152.0,99.5,39039.0,0.5,NaN,NaN

In [20]:
enhanced_box_office_data = enhanced_box_office_data.dropna()

In [21]:
enhanced_box_office_data.describe()

# all the data types seem to have parsed correctly

,Rank,$Worldwide,$Domestic,Domestic %,$Foreign,Foreign %,Rating,Vote_Count
count,4830.000000,4.830000e+03,4.830000e+03,4830.000000,4.830000e+03,4830.000000,4830.000000,4830.000000
mean,99.472257,1.218266e+08,4.591478e+07,36.307847,7.591160e+07,63.691222,6.510418,2531.585921
std,57.804538,2.032829e+08,7.824738e+07,30.531233,1.354001e+08,30.530666,0.951805,3946.272827
min,1.000000,1.666028e+06,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,49.000000,2.504339e+07,2.043532e+05,0.425000,1.394887e+07,42.000000,6.011000,205.250000
50%,99.000000,4.954631e+07,1.909036e+07,37.800000,3.046118e+07,62.200000,6.600000,1035.500000
75%,149.750000,1.231672e+08,5.535464e+07,58.000000,7.461240e+07,99.575000,7.107750,3065.000000
max,200.000000,2.799439e+09,9.366622e+08,100.000000,1.993811e+09,100.000000,9.700000,36753.000000

In [22]:
enhanced_box_office_data.to_csv('data/02-processed/enhanced-box-office-data-2000-2024-cleaned.csv')

## Ethics

### A. Data Collection
 - [] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

> There are no human subjects for this study, as the dataset contains movie cast, director, and information. We will likely scrape the IMDB ratings for each movie.

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

> We will have to do some exploratory data analysis and clean up the data to account for any outliers/bias.

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

> Our dataset doesn't have any individual ratings from viewers, so we do not have to worry about PII exposure.

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

> Our dataset is movie information and ratings, so we do not have access to any individual rating information. We probably would not have to account for this, as we are mainly working with the movie information.

### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

> We are mainly downloading the csv and storing that locally on our laptops; the code to process our data will be pushed to github.

 - [X] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?

> We do not have personal information in our dataset, as our dataset is for movies.

 - [X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

> We will likely delete the dataset from our local laptops after the project is done.

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

> We mainly are doing analysis on the dataset, so we haven't really found a need to engage with any stakeholders in this project - we aren't working with any human subjects.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> We will have to do some exploratory data analysis to see if the data is skewed towards certain types of movies. We will also have to further explore any confounding variables within the dataset.

 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

> Yes, our dataset does not contain any PIIs.

 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

 We have tried to avoid blatantly discriminatory variables, and we do believe major awards are a fair measure of an actor/actress's professional standing. While these may reflect systemic biases regarding which actors/actresses actually get their moments on big screens, these do not impact our objectives. We recognize that historical inequities exist in our metrics so we will avoid statements saying that award wins represents true talent/quality.
 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
 We do plan on testing our model results across different groups.
 - [X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [X] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?
We will aim to break down our complex understandings of different models so that readers across different backgrounds can understand.

### E. Deployment
 - [X] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 We would monitor our results over time across new ratings for film releases and as future awards are given. We will see if our discovered relationship (or lack thereof) continues or changes in the future.
 - [X] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 One concern is that maybe film studios use our results when making hiring decisions (choosing celebrities vs non-celebrities based on our results). This has the potential to hurt groups of actors/actresses. We will make sure to emphasize the limitations of our work as well as the scope to act as safeguards.
 - [X] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?
 Similar to E.2, we recognize the risk of our findings being misused for preferential hiring practices. We will make sure we state that our work is just a statistical analysis, not direct proof of any form of causation.

## Team Expectations

* Our team will mainly communicate through Imessage and call weekly for updates/syncs.
* We will communicate respectively and discuss as a group every time conflicts arise, so that we are all on the same page and we avoid escalating conflict.
* Our group expects each person to contribute equally and communicate if they are blocked or unable to do something. We center our expectations around communication - if you are unable to complete something, tell the group so that someone else can take over that part.

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/20  |  1 PM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/26  |  10 AM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/1  | 10 AM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/17  | 6 PM  | Import & Wrangle Data; EDA | Review/Edit wrangling/EDA; Refine research question and hypothesis   |
| 2/25  | 12 PM  | Finalize wrangling/EDA; Begin Analysis | Discuss/edit Analysis; Complete project check-in |
| 3/13  | 12 PM  | Complete analysis; Draft results/conclusion/discussion | Discuss/edit full project |
| 3/20  | Before 11:59 PM  | NA | Turn in Final Project & Group Project Surveys |